#!/usr/bin/perl

use strict;
use File::stat;

my @whitelisted = ();
my $whitefile = "./whitelist.txt";
my $old = 0; 

my %ips = ();

open(F1, ">/tmp/ip.log");
while(1) {
 open(F,"netstat -ntu | awk '{print \$5}' | cut -d: -f1 | sort | uniq -c | sort -n|");
 while(<F>) {
  chomp;
  /(\d+?)\ (.*)$/;
  next if $2 eq "127.0.0.1";
  my $skip = 0; 

  if (-f $whitefile) {
   my $tsp = stat($whitefile)->mtime;
   if ($old < $tsp) {
    $old = $tsp; 
    @whitelisted = ();
    open(F, $whitefile); 
    while(<F>) {
     chomp; 
     next if /^$/;
  
     # actually clear if it is already in iptables
     if (-f "./ipdelrule") {
      print `./ipdelrule $_`;
     }

     push(@whitelisted, $_);
    }
   }
  }

  foreach(@whitelisted) {
   if ($2 =~ /^$_/) {
    print F1 "Skipped whitelisted: $1 => $2\n";
    $skip = 1; 
    last; 
   }
  }
  next if $skip;
  next if $1 < 20;
  next if $ips{$2};
  $ips{$2} = 1;
  `iptables -A INPUT -p tcp  --source $2 --dport 80 -j REJECT`;
  print F1 "Blocked: $1 => $2\n";
}
 close F;
 sleep 1;
}
close F1;
